{
    "docs": "https://docs.ansible.com/ansible/2.11/dev_guide/testing/sanity/ignores.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test ignores` [[explain](https://docs.ansible.com/ansible/2.11/dev_guide/testing/sanity/ignores.html)] failed with 106 errors:", 
            "output": "tests/sanity/ignore-2.11.txt:1:1: File 'plugins/modules/import_eks.py' does not exist\ntests/sanity/ignore-2.11.txt:2:1: File 'plugins/modules/import_eks.py' does not exist\ntests/sanity/ignore-2.11.txt:3:1: File 'plugins/modules/import_eks.py' does not exist\ntests/sanity/ignore-2.11.txt:4:1: File 'plugins/modules/import_eks.py' does not exist\ntests/sanity/ignore-2.11.txt:5:1: File 'plugins/modules/import_eks.py' does not exist\ntests/sanity/ignore-2.11.txt:6:1: File 'plugins/module_utils/import_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:7:1: File 'plugins/module_utils/import_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:8:1: File 'plugins/module_utils/import_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:9:1: File 'plugins/module_utils/import_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:10:1: File 'plugins/module_utils/import_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:11:1: File 'plugins/module_utils/import_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:12:1: File 'plugins/module_utils/addon_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:13:1: File 'plugins/module_utils/addon_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:14:1: File 'plugins/module_utils/addon_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:15:1: File 'plugins/module_utils/addon_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:16:1: File 'plugins/module_utils/addon_utils.py' does not exist\ntests/sanity/ignore-2.11.txt:17:1: File 'plugins/module_utils/managedcluster_addons/addon_base.py' does not exist\ntests/sanity/ignore-2.11.txt:18:1: File 'plugins/module_utils/managedcluster_addons/addon_base.py' does not exist\ntests/sanity/ignore-2.11.txt:19:1: File 'plugins/module_utils/managedcluster_addons/addon_base.py' does not exist\ntests/sanity/ignore-2.11.txt:20:1: File 'plugins/module_utils/managedcluster_addons/addon_base.py' does not exist\ntests/sanity/ignore-2.11.txt:21:1: File 'plugins/module_utils/managedcluster_addons/addon_base.py' does not exist\ntests/sanity/ignore-2.11.txt:22:1: File 'plugins/module_utils/managedcluster_addons/addon_base.py' does not exist\ntests/sanity/ignore-2.11.txt:23:1: File 'plugins/module_utils/managedcluster_addons/application_manager.py' does not exist\ntests/sanity/ignore-2.11.txt:24:1: File 'plugins/module_utils/managedcluster_addons/application_manager.py' does not exist\ntests/sanity/ignore-2.11.txt:25:1: File 'plugins/module_utils/managedcluster_addons/application_manager.py' does not exist\ntests/sanity/ignore-2.11.txt:26:1: File 'plugins/module_utils/managedcluster_addons/application_manager.py' does not exist\ntests/sanity/ignore-2.11.txt:27:1: File 'plugins/module_utils/managedcluster_addons/application_manager.py' does not exist\ntests/sanity/ignore-2.11.txt:28:1: File 'plugins/module_utils/managedcluster_addons/application_manager.py' does not exist\ntests/sanity/ignore-2.11.txt:29:1: File 'plugins/module_utils/managedcluster_addons/cert_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:30:1: File 'plugins/module_utils/managedcluster_addons/cert_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:31:1: File 'plugins/module_utils/managedcluster_addons/cert_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:32:1: File 'plugins/module_utils/managedcluster_addons/cert_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:33:1: File 'plugins/module_utils/managedcluster_addons/cert_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:34:1: File 'plugins/module_utils/managedcluster_addons/cert_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:35:1: File 'plugins/module_utils/managedcluster_addons/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:36:1: File 'plugins/module_utils/managedcluster_addons/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:37:1: File 'plugins/module_utils/managedcluster_addons/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:38:1: File 'plugins/module_utils/managedcluster_addons/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:39:1: File 'plugins/module_utils/managedcluster_addons/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:40:1: File 'plugins/module_utils/managedcluster_addons/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:41:1: File 'plugins/module_utils/managedcluster_addons/iam_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:42:1: File 'plugins/module_utils/managedcluster_addons/iam_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:43:1: File 'plugins/module_utils/managedcluster_addons/iam_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:44:1: File 'plugins/module_utils/managedcluster_addons/iam_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:45:1: File 'plugins/module_utils/managedcluster_addons/iam_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:46:1: File 'plugins/module_utils/managedcluster_addons/iam_policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:47:1: File 'plugins/module_utils/managedcluster_addons/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:48:1: File 'plugins/module_utils/managedcluster_addons/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:49:1: File 'plugins/module_utils/managedcluster_addons/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:50:1: File 'plugins/module_utils/managedcluster_addons/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:51:1: File 'plugins/module_utils/managedcluster_addons/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:52:1: File 'plugins/module_utils/managedcluster_addons/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:53:1: File 'plugins/module_utils/managedcluster_addons/policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:54:1: File 'plugins/module_utils/managedcluster_addons/policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:55:1: File 'plugins/module_utils/managedcluster_addons/policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:56:1: File 'plugins/module_utils/managedcluster_addons/policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:57:1: File 'plugins/module_utils/managedcluster_addons/policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:58:1: File 'plugins/module_utils/managedcluster_addons/policy_controller.py' does not exist\ntests/sanity/ignore-2.11.txt:59:1: File 'plugins/module_utils/managedcluster_addons/search_collector.py' does not exist\ntests/sanity/ignore-2.11.txt:60:1: File 'plugins/module_utils/managedcluster_addons/search_collector.py' does not exist\ntests/sanity/ignore-2.11.txt:61:1: File 'plugins/module_utils/managedcluster_addons/search_collector.py' does not exist\ntests/sanity/ignore-2.11.txt:62:1: File 'plugins/module_utils/managedcluster_addons/search_collector.py' does not exist\ntests/sanity/ignore-2.11.txt:63:1: File 'plugins/module_utils/managedcluster_addons/search_collector.py' does not exist\ntests/sanity/ignore-2.11.txt:64:1: File 'plugins/module_utils/managedcluster_addons/search_collector.py' does not exist\ntests/sanity/ignore-2.11.txt:65:1: File 'plugins/modules/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:66:1: File 'plugins/modules/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:67:1: File 'plugins/modules/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:68:1: File 'plugins/modules/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:69:1: File 'plugins/modules/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:70:1: File 'plugins/modules/cluster_proxy.py' does not exist\ntests/sanity/ignore-2.11.txt:71:1: File 'plugins/modules/cluster_management_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:72:1: File 'plugins/modules/cluster_management_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:73:1: File 'plugins/modules/cluster_management_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:74:1: File 'plugins/modules/cluster_management_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:75:1: File 'plugins/modules/cluster_management_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:76:1: File 'plugins/modules/cluster_management_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:77:1: File 'plugins/modules/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:78:1: File 'plugins/modules/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:79:1: File 'plugins/modules/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:80:1: File 'plugins/modules/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:81:1: File 'plugins/modules/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:82:1: File 'plugins/modules/managed_serviceaccount.py' does not exist\ntests/sanity/ignore-2.11.txt:83:1: File 'plugins/modules/managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:84:1: File 'plugins/modules/managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:85:1: File 'plugins/modules/managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:86:1: File 'plugins/modules/managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:87:1: File 'plugins/modules/managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:88:1: File 'plugins/modules/managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:89:1: File 'plugins/modules/managedcluster_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:90:1: File 'plugins/modules/managedcluster_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:91:1: File 'plugins/modules/managedcluster_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:92:1: File 'plugins/modules/managedcluster_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:93:1: File 'plugins/modules/managedcluster_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:94:1: File 'plugins/modules/managedcluster_addon.py' does not exist\ntests/sanity/ignore-2.11.txt:95:1: File 'plugins/inventory/ocm_managedcluster.py' does not exist\ntests/sanity/ignore-2.11.txt:96:1: File 'plugins/inventory/ocm_managedcluster.py' does not exist\ntests/sanity/ignore-2.11.txt:97:1: File 'plugins/inventory/ocm_managedcluster.py' does not exist\ntests/sanity/ignore-2.11.txt:98:1: File 'plugins/inventory/ocm_managedcluster.py' does not exist\ntests/sanity/ignore-2.11.txt:99:1: File 'plugins/inventory/ocm_managedcluster.py' does not exist\ntests/sanity/ignore-2.11.txt:100:1: File 'tests/unit/plugins/modules/test_managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:101:1: File 'tests/unit/plugins/modules/test_managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:102:1: File 'tests/unit/plugins/modules/test_managed_serviceaccount_rbac.py' does not exist\ntests/sanity/ignore-2.11.txt:103:1: File 'tests/integration/targets/multicluster_management/tasks/rbac/role.yaml' does not exist\ntests/sanity/ignore-2.11.txt:104:1: File 'tests/integration/targets/multicluster_management/tasks/rbac/rolebinding.yaml' does not exist\ntests/sanity/ignore-2.11.txt:105:1: File 'tests/unit/plugins/modules/fixtures/rbac_template/bad_rbac.yml' does not exist\ntests/sanity/ignore-2.11.txt:106:1: File 'tests/unit/plugins/modules/fixtures/rbac_template/five_object_file.yml' does not exist"
        }
    ], 
    "verified": false
}
